import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis'
import { useEffect } from 'react'


export default function Home() {
  const { isAuthenticated, authenticate } = useMoralis()
  const router = useRouter()
  
  useEffect(() => {
    if(isAuthenticated){
      router.push('/dashboard')
    } 
  }, [isAuthenticated, router])


  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello World</h1>
      <button 
        className="px-7 py-4 text-3xl rounded-xl bg-green-400 animate-pulse"
        onClick={() => authenticate({
          signinMessage: "Authorize linking of your wallet!"
        })}
      >
        Moralis Provider - Login using Metamask
      </button>

    </div>
  )
}
